[tool.poetry]
name = "socketify-imya-mne-skorost"
version = "1.0.0"
description = ""
authors = ["Denis Anikin <ad@xfenix.ru>"]

[tool.poetry.dependencies]
python = "^3.11"
socketify = "*"
msgspec = "*"
redis = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
