version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:80"
    networks:
      - webnet

  nginx:
    image: nginx:1.25.3-bookworm
    container_name: litestar-nginx-proxy
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - app
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf

  redis:
    image: redis:7.2.2-bookworm
    networks:
      - webnet
    command: redis-server --save "" --maxmemory 2gb --appendonly yes --maxmemory-policy allkeys-lfu

networks:
  webnet:
